# Generated by Django 5.0 on 2023-12-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_contact_education_experience_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='cv_attachment',
        ),
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.CharField(default='Address', max_length=255),
        ),
        migrations.AddField(
            model_name='cv',
            name='first_name',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='last_name',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone_number',
            field=models.CharField(default='Null', max_length=15),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.TextField(default='Null'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.TextField(default='Null'),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.TextField(default='Null'),
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
